#!/usr/bin/python

def pig_latin(word):
    
    first_letter=word[0]
    if first_letter in 'aeiou':
       pig_word=word+'ay'
    else:
       pig_word=word[1:]+first_letter+'ay'
    return pig_word

result=pig_latin('apple')
result1=pig_latin('Hemanth')

print(result)
print(result1)


    
